### ISSUE TITLE
Adding alternatives to landing page?

### ISSUE THREAD

**Issue by jakemmarsh** [ramonsaraiva/missinboxalready#1]
I'm equally bummed about Inbox going away, but I am aware of a few companies working on alternatives/improvements. Would you be open to adding links to some of them here? One example is https://monolist.co

**Comment by ramonsaraiva** [comment]
hey Jake, i wouldn't mind, monolist seems neat.
would you mind creating a pull request or a simple mock exemplifying where those could be located?
